version: '3.8'

services:
  frontend:
    build: /frontend
    restart: always 
    ports:
      -"80:80"
    depends_on:
      - backend
  backend :
    build: /backend
    restart: always
    env_file:
    - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      -db_data:var/lib/mysql
  volumes:
    db_data:
  